Override orientation to be portrait before build
This is needed because building with landscape orientation props set results in the error "Could not find ui.xml for TW_THEME: landscape_hdpi", so just force the orientation to be portrait.

Signed-off-by: Eyad Tamer <eyadtamer2121@gmail.com>

diff --git a/.github/workflows/OrangeFox-X505X-Compile.yml b/.github/workflows/OrangeFox-X505X-Compile.yml
--- a/.github/workflows/OrangeFox-X505X-Compile.yml
+++ b/.github/workflows/OrangeFox-X505X-Compile.yml
@@ -73,6 +73,29 @@ jobs:
         cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
         git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
 
+    - name: Patch BoardConfig for Portrait Mode
+      run: |
+        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
+
+        BOARD_FILE=$(grep -rl "TW_THEME" ${{ inputs.DEVICE_PATH }} | grep BoardConfig || true)
+
+        if [ -z "$BOARD_FILE" ]; then
+          echo "::error::BoardConfig file not found!"
+          exit 1
+        fi
+
+        echo "Editing $BOARD_FILE"
+
+        # Replace theme
+        sed -i 's/TW_THEME[[:space:]]*:?=[[:space:]]*landscape_hdpi/TW_THEME := portrait_hdpi/g' "$BOARD_FILE"
+
+        # Comment rotation related variables if present
+        sed -i 's/^\(.*TW_ROTATION.*\)$/#\1/g' "$BOARD_FILE"
+        sed -i 's/^\(.*RECOVERY_TOUCHSCREEN_SWAP_XY.*\)$/#\1/g' "$BOARD_FILE"
+        sed -i 's/^\(.*RECOVERY_TOUCHSCREEN_FLIP_Y.*\)$/#\1/g' "$BOARD_FILE"
+
+        echo "BoardConfig patched successfully."
+
     - name: Building OrangeFox
       run: |
         cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ inputs.MANIFEST_BRANCH }}
